### ISSUE TITLE
现在每个token只能处理两张照片了。。。

### ISSUE THREAD

**Issue by roryshanshan** [huanghaozi/AutoMatting#1]
感谢大神的工具，非常好用，但是今天开着全局代理，速度足够快。但是第三张图片就是bad request 以及too many request 的报错，换个token又能来两张，我觉得是不是处理时间过快导致的，麻烦大神看看

**Comment by huanghaozi** [comment]
啊这，我感觉可能是代理的原因

**Comment by roryshanshan** [comment]
> 啊这，我感觉可能是代理的原因

换了好几个地区节点都一样。。。
