### ISSUE TITLE
似乎。。。效果有待优化？一个新的想法（或许可行？）

### ISSUE THREAD

**Issue by taozhiyu** [huanghaozi/AutoMatting#5]
![image](https://user-images.githubusercontent.com/49258735/196081383-169beca9-634c-4ae2-b7bf-b84108700ac5.png)
左图是缩略图下载的样子，右图是本软件生成的，可以看到有蓝色的底色毛边（和阿里妈妈处理的效果差不多）

![image](https://user-images.githubusercontent.com/49258735/196081648-e0b64f25-76a9-4402-bc76-e4353da79755.png)
（上图为阿里妈妈抠图的效果）

或许可以通过蒙版获取需要裁剪的边框，计算合适的大小进行拆分，将每一张包含边界的图片上传进行处理（理论上图片像素小于 25w 就可以下载“高清图”），之后再讲下载后的图片重新拼接起来。。。。

或许api的次数就有点不够了，或许就需要通过模拟提交或者分析数据接口了（反正python配上一个chrome绿色版再加一个配套的驱动一打包就行。。。）（或者就直接用electron外部操作网页。。。）

注：
> 上两张图所涉及的四个头像（部分）均为我朋友的照片。。。
> 已经打码了，如果还是感觉被冒犯了，那就忍着吧 😄

**Comment by huanghaozi** [comment]
哈哈哈，现在看其实有很多开源的深度学习模型可以用（太卷辣），找个好点的模型完全可以离线本地运行，很多手机都带一键抠图功能了
